name: Terraform

on:
  pull_request:
    pushes:
      main
  push:
    branches:
      main

jobs:
  validate-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform
      
      - name: Terraform Plan
        run: terraform plan -var="github_organization=AustinBlob" -var="github_token=${{ secrets.TERRAFORM_GITHUB_TOKEN }}"
        working-directory: ./terraform
