name: Terraform

on:
  pull_request:
    pushes:
      main
  push:
    branches:
      main

jobs:
  validate-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.1
      
      - name: Terraform login
        run: |
          echo $TFC_API_TOKEN | terraform login
        env:
          TFC_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform
      
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform
